baseURL = '/'
languageCode = 'en-us'
title = 'Ayaan Ali'
theme = 'terminal'
copyright = "© 2025 Ayaan Ali. All rights reserved."

[menu]

    [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"

    [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"

    [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    
    [[menu.main]]
    identifier = "CV"
    name = "CV"
    url = "resume/Ayaan_Ali_CV_August2025.pdf"

[caches]
  [caches.images]
    dir = ':cacheDir/images'